services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ittp_db
      POSTGRES_USER: ittp_user
      POSTGRES_PASSWORD: ittp_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: